server:
  port: 8080

spring:
  application:
    name: registration-service
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:authz.pub