version: 0.2

env:
  variables:
    BASE_REPOSITORY_URI: 124984100580.dkr.ecr.us-east-1.amazonaws.com/lkksoftdev/vsbba

phases:
  install:
    commands:
      - echo Fetching additional commit...
      - git fetch --depth=2

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - DOCKER_PASSWORD=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - |
        for server in account-service api-gateway beneficiary-service config-server eureka-server external-service loan-service registration-service; do
          if git diff --quiet HEAD^ HEAD $server/; then
            echo "Building $server"
            REPOSITORY_URI=$BASE_REPOSITORY_URI/$server
            cd $server
            mvn spring-boot:build -DskipTests
            docker tag $(docker images -q | head -n 1) $REPOSITORY_URI:latest
            docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
            cd ..
          fi
        done

  post_build:
    commands:
      - |
        for server in account-service api-gateway beneficiary-service config-server eureka-server external-service loan-service registration-service; do
          if git diff --quiet HEAD^ HEAD $server/; then
            echo "Pushing $server"
            REPOSITORY_URI=$BASE_REPOSITORY_URI/$server
            echo $DOCKER_PASSWORD | docker login --username AWS --password-stdin $REPOSITORY_URI
            docker push $REPOSITORY_URI:latest
            docker push $REPOSITORY_URI:$IMAGE_TAG
          fi
        done