version: 0.2

env:
  variables:
    BASE_REPOSITORY_URI: 124984100580.dkr.ecr.us-east-1.amazonaws.com/lkksoftdev/vsbba

phases:
  install:
    commands:
      - echo Fetching additional commit...
      - git fetch --depth=2
      - echo Checking for changes in the server directories...
      - |
        for server in account-service api-gateway beneficiary-service config-server eureka-server external-service loan-service registration-service; do
          if git diff --quiet HEAD^ HEAD $server/; then
            echo "Changes detected in $server"
            echo "##[set-output name=$server;isOutput=true]"
          fi
        done

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region $AWS_DEFAULT_REGION --no-include-email)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - |
        for server in account-service api-gateway beneficiary-service config-server eureka-server external-service loan-service registration-service; do
          if [ "$(echo ${{ steps.check.outputs.$server }})" == "true" ]; then
            echo "Building $server"
            REPOSITORY_URI=$BASE_REPOSITORY_URI/$server
            cd $server
            mvn spring-boot:build -DskipTests
            docker build -t $REPOSITORY_URI:latest .
            docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
          fi
        done

  post_build:
    commands:
      - |
        for server in account-service api-gateway beneficiary-service config-server eureka-server external-service loan-service registration-service; do
          if [ "$(echo ${{ steps.check.outputs.$server }})" == "true" ]; then
            echo "Pushing $server"
            REPOSITORY_URI=$BASE_REPOSITORY_URI/$server
            docker push $REPOSITORY_URI:latest
            docker push $REPOSITORY_URI:$IMAGE_TAG
          fi
        done