
services:
  db:
    image: mysql:8.3
    container_name: sba-banking-system
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sbavirtusa_pw
      MYSQL_DATABASE: sbavirtusa_db
      MYSQL_USER: sbavirtusa_user
      MYSQL_PASSWORD: sbavirtusa_pw
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - sba_network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - sba_network

networks:
  sba_network:


#  eureka-server:
#    image: lkksoftdev/vsbba/eureka-server:0.0.1-SNAPSHOT
#    container_name: eureka-server
#    ports:
#      - "8761:8761"
#    networks:
#      - sba_network
#    depends_on:
#      - db
#
#  config-server:
#    image: lkksoftdev/vsbba/config-server:0.0.1-SNAPSHOT
#    container_name: config-server
#    ports:
#      - "8888:8888"
#    volumes:
#      - /Users/lahirukk/SoftwareProjects/SpringBootBankingSystemComplete/VSBBS-git-config-repo:/config-repo
#    networks:
#      - sba_network
#    depends_on:
#      - eureka-server
#    environment:
#      SPRING.CLOUD.CONFIG.SERVER.GIT.URI: /config-repo
#      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: "http://eureka-server:8761/eureka"