server:
  port: 8765

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ["http://localhost:5173", "https://app.lkksoftdev.xyz"]
            allowedMethods: "*"
            allowedHeaders: "*"
